### ISSUE TITLE
Can't connect past logging in... connect ETIMEDOUT

### ISSUE THREAD

**Issue by pironic** [UlysseM/GSBOT#27]
Running windows 8.1 x64 with node.js installed, it appears to login, but then can't connect further. I've disabled the firewall on this computer without any luck.

have you got any suggestions?

    Starting GSBOT
    Logged successfully as Michael Writhe #2
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: connect ETIMEDOUT
        at exports._errnoException (util.js:746:11)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
    Press any key to continue . . .

**Comment by UlysseM** [comment]
Was it an issue on your side / is it fixed?

**Comment by pironic** [comment]
still outstanding on my win 8.1 comp. I'm deving on a win 7 comp to get around it.

**Comment by UlysseM** [comment]
Strange, I'm on win 8.1x64 with node v0.10.29, (node v0.10.36 on my debian server), and I have absolutely no error.

If there is an issue, it's either from your configuration or from nodejs itself...

Full version:
{ http_parser: '1.0',
  node: '0.10.29',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.27',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1h',
  npm: '1.4.14' }

and
{ http_parser: '1.0',
  node: '0.10.36',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.30',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1l',
  npm: '1.4.28' }

**Comment by pironic** [comment]
no idea. used a different machine.

**Comment by UlysseM** [comment]
For the record: https://github.com/joyent/node/issues/9216
