### ISSUE TITLE
addToCollection

### ISSUE THREAD

**Issue by Fubar69** [UlysseM/GSBOT#31]
This is really really handy for a bc like mine where I have a seperate account hosting the BC. This way I can continue to increase my collection for the bot to choose from.

**Comment by UlysseM** [comment]
You can actually log in with your main account (and click on take over) while the bot is working. The bot will still be working find, and you can even change the queue from groveshark.

That being said, I'm working on it!

**Comment by UlysseM** [comment]
Done.
