### ISSUE TITLE
Event Silence

### ISSUE THREAD

**Issue by pironic** [UlysseM/GSBOT#33]
during an event  we should silence all output not initiated by a broadcaster or guest

**Comment by UlysseM** [comment]
what do you mean by "event" ?

**Comment by pironic** [comment]
Event as in special event. Sometimes some of the broadcasts get special guests that pick the songs for an hour.

**Comment by UlysseM** [comment]
/beQuiet, by default for whiteListed people, on the plugin 'quiet'.
