### ISSUE TITLE
Contest Functionality

### ISSUE THREAD

**Issue by pironic** [UlysseM/GSBOT#34]
3 commands to implement

/startContest - will start a contest by toggling the contestRunning var, and announce it's open.
/endContest - will randomly choose a userID and lookup their name from the array of entries then set the contestRunning to false.
/ballot - if called by a guest will output how many entries we have so far, if called by isListener it'll add their userID to an array.

when endContest is called, it'll toggle the 'contestRunning' variable and pull a random userID from the array we've collected from /ballot.

**Comment by UlysseM** [comment]
This should be in a separate plugin.

**Comment by pironic** [comment]
I completely agree. I was just going to create the issue to keep track of the module... Coming functionality.

**Comment by gsclassics** [comment]
Great to see both working together :)
Did you know GrooveCaster? https://github.com/OrfeasZ/GrooveCaster
It is managed from a Web UI and it is gonna be really usable!

**Comment by UlysseM** [comment]
I am aware of its existence. I just don't care about it.
