### ISSUE TITLE
fetchLast

### ISSUE THREAD

**Issue by pironic** [UlysseM/GSBOT#35]
to replicate the functionality built on the writhem bot we'd like to say:

/fetchLast - will fetch the last 1 entry.
/fetchLast 5 - will fetch the last 5 entries in the order they are currently showing.
/fetchLast !5 - will fetch the last 5 entries in reverse order.

**Comment by Fubar69** [comment]
The new GS lets you suggest and add the song to the end or to the next track so I am not sure this command is needed?

**Comment by pironic** [comment]
let's imagine you're utilizing the playPlaylist command and adding 10 songs to the queue. It'll add them to the end of the queue. now you want 5 of those to be next, in reverse order. what do?

**Comment by UlysseM** [comment]
Fully implemented.
