### ISSUE TITLE
reloadPlugin

### ISSUE THREAD

**Issue by pironic** [UlysseM/GSBOT#36]
/reloadPlugin <name> to --- reload the plugin from disk.

**Comment by UlysseM** [comment]
I thought about that one. Especially useful for the dev. The fact you can restart the bot in +/- 5 seconds offered me a quick workaround, also, if a plugin loads some data, this could get messy with the mod.init().

**Comment by pironic** [comment]
maybe not so much a /reloadPlugin command then, but a /reloadBot?

**Comment by UlysseM** [comment]
Well, in which case would you want to reload it? I'm taking it would be when you update a script, so doing a Ctrl-C and restarting it could suffice. It could lead to some trouble if some people abuse from such a function...
