### ISSUE TITLE
Bot returns [Object object] in response to stats occasionally

### ISSUE THREAD

**Issue by swimmadude66** [UlysseM/GSBOT#41]
Looks as though this block in stats.js is responsible 
```
res.on('data', function (chunk) {
                    request.sendChat(chunk);
                });
```

**Comment by UlysseM** [comment]
@pironic

**Comment by Reanmachine** [comment]
I recall reporting this to @pironic directly the other day, I think he's working on it.

**Comment by pironic** [comment]
There is an associated commit which i'm just finalizing in the GSBOT-php-lib repository. I was throwing header error codes incorrectly, but that has been resolved.
