### ISSUE TITLE
Plugin or Core code to have a configurable threshold for song recurrence

### ISSUE THREAD

**Issue by Reanmachine** [UlysseM/GSBOT#42]
It seems the bot's random / play mode is true random sometimes (depending on what's going on), I've noticed on many occasions it'll play the same song multiple times within the same hour and people get quite annoyed (especially if it's a low-vote song).

It would be nice to have something that keeps track of the songs played over a period of time and makes sure it doesn't play the same thing (either simply /skip ing, or keeping the queue from scheduling the same song if there's others to choose from).

**Comment by pironic** [comment]
Ahh yeah, we used to do that. we'd have a separate array we kept the songs in and checked the array before adding a song to the queue. If i remember correctly, it used to be 50 songs long.

Because this a core function, i'll leave until i receive direction from @UlysseM

**Comment by Reanmachine** [comment]
It would probably be simpler to keep a queue of the last N songs played and just re-select a song if the selected song is in that list, then you don't have a problem with the next queue becoming stale.

**Comment by UlysseM** [comment]
I knew I'd have that request soon or later!
I'll try to patch it soon.

Oh and while I'm taking about some things I'm expecting request, whenever the broadcast doesn't comply with the rules, I just turn off the mobile for an hour.
Right now, it would be confusing / really difficult for guest to understand why the song they approved didn't play / reorder the queue that they cannot see at the moment.
It would also be confusing to as it would cause the broadcast to stop on some occasions: the bot makes a request to add a song to the queue, few seconds later, the server answer "you can't play that!", and I'll just retry until I find something that fits. With small collection, the broadcast would just die after 20ish minutes or so.

James plans to implement in the future a way for guest to see and modify the queue directly, I could try to make a variable in the config to 'never turn off the broadcast on mobile', but still, I make no plans / guarantee.

**Comment by Reanmachine** [comment]
Just encountered the behavior on a bot running commit a9185be31f4bb8b94ef6940c4a60961d82e5758c, it's still repeating songs: http://i.imgur.com/Gh0X2op.png

We probably need to look at this one again.
