### ISSUE TITLE
[Plugin] /records To keep track of milestones in a channel.

### ISSUE THREAD

**Issue by Reanmachine** [UlysseM/GSBOT#50]
Would be nice to have this feature (We had it in WritheM previously)

`/records` would display stats like:

* Highest User Count / Time
* Most Upvoted Song
* Most Downvoted Song
* Highest contention voted song (most up/down votes closest to 0 sum, ie. the most contraversal song)
* Most upvoted suggestion(s) ?

This could be part of the stats thing @pironic is working on or it's own plugin.

Perhaps with a `/resetrecords` command for clearing them all / individually.

**Comment by UlysseM** [comment]
it would be a neat idea! Right now, such plugin could be written without touching the core, which is the point I wanted to push the core to.

It's a perfect timing as I'm about to get really busy IRL, and will likely just patch the core and the default plugins if grooveshark evolves and break some things.

You could try implementing that!

**Comment by Reanmachine** [comment]
I suppose I could... maybe I'll try my hand at this one tonight.

**Comment by UlysseM** [comment]
I see two ways of doing this, well, three...

* Create a small file to store those data, whenever callback are called, check for new stuff.
* Do it with an external DB (such as @pironic 's php module)
* Have me building as a part of the core a pretty unefficient database with nodejs, where you can just get an javascript object and store it, whenever you want, that will persist upon reboots.

**Comment by Reanmachine** [comment]
I was going to use a json flat file on disk, but as a matter of completeness wouldn't it be prudent to utilize something like a sqlitedb for random crap the bot wants to store, keeping things central / contained?

**Comment by pironic** [comment]
@reanmachine, look into the php stuff i did... i did intend to keep the
records stored on the sharkcommunity db as well. I just havn't gotten
around to it yet. If you want to build off that, i'd be happy to deploy
anything you code.

The way i was going to do it, is check what the current records are on
init, then keep those local until they are broken. when they are, post an
update to the database. It'd be a simple 1 value per type thing... but then
i started thinking about the possibility of logging stuff more indepth. It
would be neat to see the graphs i have in real time of listener counts and
peak periods per broadcast. (all contained on the community stats section).
I'm just worried that it'll be too many hits for what it's worth.

**Comment by Reanmachine** [comment]
@pironic How about I make it a configuration option, so people can use the plugin without the PHP dependency, we can support both!

**Comment by pironic** [comment]
if you could do that for the whole php branch, that would be amazing :-)
dbhistory rather.

**Comment by Reanmachine** [comment]
@pironic Let's prototype it here, then worry about the other stuff! :)

**Comment by Reanmachine** [comment]
@UlysseM I've managed to complete a prototype fairly easily, there's a couple technical components that came up during development I wanted to ask you about:

1. I read in your guidelines that plugins shouldn't be using `require()`, I can't tell if you mean breaking the *core/plugin barrier* by requiring gsbot/manatee or if you mean *strictly, i.e. not importing nodejs components like `fs` or whatnot. What would be your standard process for accessing the `fs` or `http` modules from node.js?
2. It seems plugins callback methods are inconsistently being called with context, the `init()` method has context due to the way it's called, but the `onCall`, `onSongChange` etc... are not because they're being copied into a callback list. Wrapping the callbacks with a `.apply()` call would resolve this across the board in a 1 line change **I could submit as a pull request to you if you're interested** in having proper `this` context in those calls, if that's by design can you enlighten me as to why you'd want the module objects using only global calls to the module?
3. Inter-Module Communication, how are we supposed to do this? I need one command to issue calls to the non-command module to do things like save the results as this is an operation that multiple commands may want to do, and duplicating that code/config is not desired. It looks like you used to pass a `moduleList` to all the modules on init so they could in theory go get the other module instance and call methods on it but it seems that this is no longer the case because in `moduleloader.js` it doesn't appear that the list is being populated (it looks like that change was a result of a refactor or something).

If you could shed some light that'd be awesome, part of this may be my inexperience working on the project but perhaps I've identified some areas we could improve. 

Like I said, I can submit a pull request for Point 2 if you're not sure what I'm talking about, it wouldn't have any adverse effect on any existing plugins / code, it would only serve to keep things standard and correct.

-Aren

**Comment by UlysseM** [comment]
1. You can use it to access fs/http.
However, watch for collision with the file name, as multiple broadcast can run in the same path.

2. I have to admit, javascript is far from being my favorite language. The GSbot was my first try at it, and I probably know only a third of the language feature. You can do a pull request for the core, give me some time to review it.

3. On init, there is an object that is shared between all mods of a plugin. You can just place the method there and keep the reference in all your plugins so you can call them.

**Comment by Reanmachine** [comment]
@UlysseM 

1. Thanks, didn't think about that. In the future it would be ideal if the bot could provide a *path* to a broadcast/plugin specific storage space, for now I'll rig something up.

2. Ah yes, javascript is a mysterious beast, For your "first" project in JS it's looking quite good so don't fret.

3. I tried this (defined a function on `sharedObject` but ran into issues due to an unreliable load order with the modules. I'll give it another crack and see if we need to look at another avenue.

Thanks

**Comment by UlysseM** [comment]
Yeah, I have to redo all the init calls... right now, they are called as the plugins are loading, I want to call them when the broadcast is actually "ready".
