### ISSUE TITLE
[Core] Is there a way we could use an auth/oauth token or something in place of storing our passwords for the broadcasting account on disk?

### ISSUE THREAD

**Issue by Reanmachine** [UlysseM/GSBOT#51]
I'm not sure how possible it is given the GS API, but it would be nice if we could take a one-time input of user/password and store an auth token from GS instead of keeping the password(s) in plaintext on disk.

**Comment by UlysseM** [comment]
Well, we could store the ssid, the session is on it, and upon logging, replacing the "password" with the "ssid", only if the user wants it that way (sometimes, this could fail)

**Comment by Reanmachine** [comment]
Yeah, hard to say... i just noticed the password on disk after configuring and immediately all the security alarms in my head went off. With a system that needs to be automated, any kind of break in that automation (including sessions timing out / etc...) pose a problem. 

I wonder if it'd be worth 2-way encrypting the password when stored to file, it doesn't really make anything more secure but it does remove compromises of "opportunity" i.e. "oooh, I found a password on disk", and naming the key something different might protect the file against any malware that are scraping files for username/password combinations.

**Comment by UlysseM** [comment]
well, on my linux server, the bot runs on a dedicated user with the right of the config file at 600. So having it stored in plain text is as secure as my root password, as long as someone doesn't physically take the hard drive out of the server, yet again, the grooveshark password stored on my server are the least important things, as a mail to the support is enough to gain it back, if someone happens to steal it and change it.

**Comment by Reanmachine** [comment]
Well yes, I did say it didn't really change anything security-wise, it just helped stop attacks of oppurtunity, any determined person will break through a 2-way encryption where the key is stored locally (memory/disk/etc...) with ease.

I just wanted to raise the discussion because I can see people who aren't as well versed in proper security as you or I using it with no protections and getting their password stolen, which may also be the same password as other services (Which is a larger problem).

**Comment by UlysseM** [comment]
In order to be completely runable by a script, and prevent 'accidental peek', I'm guessing encrypting the password by a hash of the username would be sufficient.

**Comment by UlysseM** [comment]
I mean it's completely not safe, as people could just write two lines of code to print it, but it's as secure as converting the password to base64 and doing a rot13 of that.

**Comment by Reanmachine** [comment]
Since it's largely ineffective, just a nice thing to filter out the lazy, I wouldn't spend too much time on it...
