### ISSUE TITLE
manatee.broadcastDesc = lastBroadcast.Description - null error

### ISSUE THREAD

**Issue by webdevbrian** [UlysseM/GSBOT#53]
hi,

keep getting this error after configuring everything, wondering what's going on.

thanks!

    [ERR]myusername: /Users/enterprise/Desktop/GSBOT/core/manatee.js:683
    [ERR]myusername:     manatee.broadcastDesc = lastBroadcast.Description;
    [ERR]myusername:
    [ERR]myusername:                                   ^
    [ERR]myusername: TypeError: Cannot read property 'Description' of null
    [ERR]myusername:     at Object.manatee.broadcast
    (/Users/enterprise/Desktop/GSBOT/core/manatee.js:683:42)

"!!!! User myusername exited with code 8"

I've replaced my actual username with "myusername" in the above errors

and then it just keeps restarting Ad nauseam

**Comment by UlysseM** [comment]
Have you ever started a broadcast with a description before starting the bot?

If not, do so.

A quick fix is also to start the broadcast manually, and then start the bot, it will take over without any interruptions.

**Comment by webdevbrian** [comment]
Hey Ulyssem - is that in the documentation anywhere?

**Comment by UlysseM** [comment]
Probably not, I'll have time to work on the bot this week end, I'll make sure to print a nice error that will explain nicely what to do instead of looping indefinitely. Did the fix worked for you?

**Comment by webdevbrian** [comment]
Awesome! thanks. Yeah -- term is spitting out stats like it's in a verbose mode of sorts.  Also, info on being able to grab UIDs and add yourself so you have permission to use the commands would be beneficial as well. I can help out any way I can if you'd like.

Thanks!

**Comment by UlysseM** [comment]
If you want to write some documentation and do a pull request, I'll be happy to merge it :)

**Comment by webdevbrian** [comment]
Ha! Nice ;)

I just need to know the basics and from there I can start putting something together - e.g. adding yourself as an admin, stock commands the bot comes with, things like that. If you can supply that I'll be more than willing to do a pull -- thanks!

**Comment by UlysseM** [comment]
Well, put it simply, you can run some commands by having some permissions. It boils down to "being guest", "being whitelisted" and "being followed by the broadcaster".
By default, people that are followed can do a "/guest" command to become a "special guest", add tracks, and perform all the commands.

**Comment by webdevbrian** [comment]
Perfect - yeah things like that have to go in the documentation :)

**Comment by UlysseM** [comment]
The bot now outputs a message that will inform the user that he needs to have completed at least one broadcast to use the bot.
