### ISSUE TITLE
GSBot Error: no_auth

### ISSUE THREAD

**Issue by Tasemu** [UlysseM/GSBOT#54]
Heya, after a fair few hours the bot always dies with the following error. :)

{"command":"pub","type":"return","return":[{"name":"082a640e8c2cec64db5dca1b68ced178","return":"error","error":"no_auth"}],"blackbox":{"_cid":223}}

**Comment by UlysseM** [comment]
I need you to give me a little more details!

This is the answer from the Grooveshark Server, what was the request the bot made (should be a green text with _cid:223, as your answer is _cid:223)?

Do you have any plugins enabled other than "default"?

What you mean by "dying", the software is still running but the broadcast dies? the bot instance crashes and restart automatically? the bot instance crash and does not restart?

Also, are you using the latest version?

**Comment by Tasemu** [comment]
Hi there, sorry about being vague haha.

Ok so:

- Only "Default" Plugin is enabled
- The software still runs but the broadcast dies :)

I will include a gist link to the terminal output momentarily.

**Comment by Tasemu** [comment]
https://gist.github.com/Tasemu/2b5e0116713eba9b2d18

you should be able to scroll to the bottom to see whats happening, but I included it from the beginning just incase you needed it.

**Comment by UlysseM** [comment]
You can remove the gist, as I have it open on an other window. Oh and no need to write down your sessionid (second line).

Did your broadcast had the same issue that time? I couldn't see any "error" on the logs.

Also, could you describe how the broadcast dies exactly?
If the songs stop playing but command such as /ping works fine, and they are still some track in the queue, try a "/skip".

**Comment by Tasemu** [comment]
I'll try to see if ping or skip happens next time. As for how it dies, i try to go onto grooveshark and I cannot find the broadcast on available broadcasts anymore. So I assume the broadcast was closed or timed out? :)

**Comment by UlysseM** [comment]
Sometime, grooveshark would hide some broadcast.
What you can do is login with the broadcaster account, and see if it asks you to takeover.
When you do takeover, if it's playing a song, chances are the bot is working fine.

Also, it copies the parameters from the previous broadcast, meaning that if the broadcast was "not advertised", it probably won't show.

An other thing, if you try to find the broadcast through the mobile app, note that grooveshark have strict rules about broadcasting for mobile devices (such as, don't play the same artist 4 times in 4 hours, don't play the same album 3 times in 3 hours). As the bot is autonomous, it will just give up, by disabling mobile broadcasts for an hour (it will work fine for the site though),

**Comment by UlysseM** [comment]
Well, I experienced the same issue as you on my computer that went to sleep while the bot was running.

The issue might be your connection between grooveshark and the bot being broken.

I'll try to push a patch that automatically restart the broadcast when such thing happens.

**Comment by Tasemu** [comment]
Ah that could be the issue. Thanks for the support! I'll disable sleep for now. :)

**Comment by UlysseM** [comment]
So, basically, when your computer is asleep, the bot is down (if its on your computer that is asleep) and your broadcast will die off when it will run out of song.

I added a feature that will recognize when such a thing happen, and will restart the bot automatically.

It won't fix the fact that the broadcast will die off, but at least, you won't need to worry about restarting the bot if this happens again.
