### ISSUE TITLE
Strange error this morning

### ISSUE THREAD

**Issue by Tasemu** [UlysseM/GSBOT#55]
Hi there!

I came home this morning to find that the bot had died with an error while I was away. This was not a problem, however when trying to restart the bot, I now get this error and cannot resume my broadcasting at all. :)

raadiome: Logged successfully as Raadio
raadiome: {"command":"identify","params":{"app_data":{"f":"0","n":"Raadio","p":"29662485-20150326012511.gif","y":"0","z":"99b67b7f"},"invisible":false,"userid":"29662485","app_sig":"1429138549:6083e75d450973e863ca372e846ee7cde6cfcc1d","sessionid":"********"},"blackbox":{"_cid":1}}
raadiome: {"command":"identify","type":"success","success":{"id":{"sudo":false,"uid":"g2dkABNtYW5hdGVlQDE3Mi4xNi4wLjgxAAB80wAAFtYD","userid":"29662485","app_data":{"f":"0","n":"Raadio","p":"29662485-20150326012511.gif","y":"0","z":"99b67b7f"}},"loggedin":true},"blackbox":{"_cid":1}}
raadiome: {"command":"set","params":{"keyvals":[{"key":"i","readable":"global","value":{"p":"29662485-20150326012511.gif","n":"Raadio","y":false}}]},"blackbox":{"_cid":2}}
raadiome: {"command":"set","type":"success","success":"set","blackbox":{"_cid":2}}
raadiome: {"command":"sub","params":{"add":true,"subs":[{"overwrite_params":false,"sub":"global"},{"overwrite_params":false,"sub":"user:29662485"}]},"blackbox":{"_cid":3}}
raadiome: {"command":"sub","type":"success","success":[{"sub":"global","params":{"a":null},"latest_messages":[]},{"sub":"user:29662485","params":{"owner_subscribed":false,"owners":[{"type":"uid","name":"g2dkABNtYW5hdGVlQDE3Mi4xNi4wLjgxAAAywQAAGIwD"}]},"latest_messages":[]}],"blackbox":{"_cid":3}}
raadiome: {"command":"get","params":{"keys":["s"],"userid":29662485},"blackbox":{"_cid":4}}
raadiome: {"command":"get","type":"return","return":{"userid":"29662485","values":[{"bcast":"552e318ec87467af3d8b4568","bcastName":"Raadio | Anime Radio Station","bcastPic":"","bcastOwner":1,"status":1,"song":null,"songEx":null,"time":1429138523638,"remora":4.6}]},"blackbox":{"_cid":4}}
raadiome: {"command":"sub","params":{"add":true,"subs":[{"create_when_dne":false,"overwrite_params":false,"sub":"bcast:552e318ec87467af3d8b4568"},{"create_when_dne":false,"overwrite_params":false,"sub":"bcast:p:552e318ec87467af3d8b4568"}]},"blackbox":{"_cid":5}}
raadiome: {"command":"sub","type":"success","success":[{"sub":"bcast:552e318ec87467af3d8b4568","params":{"se":true,"owner_subscribed":true,"sub_alert":true,"tags":["bcast","bcast_genre_1304"],"pndOwner":null,"tl":0,"p":0,"publishers":[{"type":"userid","name":"29662485"},{"type":"userid","name":"42"},{"type":"userid","name":"3879"},{"type":"userid","name":"579416"},{"type":"userid","name":"2226931"},{"type":"userid","name":"3327599"},{"type":"userid","name":"17638985"},{"type":"userid","name":"17729920"},{"type":"userid","name":"21007202"},{"type":"userid","name":"25736013"}],"n":"Raadio | Anime Radio Station","owners":[{"type":"userid","name":"29662485"}],"py":false,"d":"We chill and listen to animu tunes here...","h":{"s":[]},"t":{"i":1304,"n":"Anime"},"qc":"b308c09f66149fa8ff0277cee2ddbcdf","x":0,"s":null,"remora":"g2dkABVtYW5hdGVlQDE3Mi4xNi4xMDAuOTIAAD4VAAAJRwM=","unsub_alert":true,"liveURL":"","i":null,"v":4.6,"cp":{"photo":"55135897c87467d3108b457f-20150325211032.png","y":0,"flags":0,"stock":0}},"latest_messages":[]},{"sub":"bcast:p:552e318ec87467af3d8b4568","params":{"v":4.6,"vp":[],"ban_groups":["bcast_chat"],"sge":true,"c":true,"sgc":[],"banned":[],"store_latest":true,"owner_subscribed":true,"remora":"g2dkABVtYW5hdGVlQDE3Mi4xNi4xMDAuOTIAAD4VAAAJRwM=","sg":{"s":{},"b":[]},"sga":true,"owners":[{"type":"userid","name":"29662485"}],"publishers":"global"},"latest_messages":[]}],"blackbox":{"_cid":5}}
[ERR]raadiome: /Users/montague/raadio/core/manatee.js:703
[ERR]raadiome:                 if (ret[0].params.s.active)
[ERR]raadiome:                                    ^
[ERR]raadiome: TypeError: Cannot read property 'active' of null
[ERR]raadiome:     at /Users/montague/raadio/core/manatee.js:703:36
[ERR]raadiome:     at Array.<anonymous> (/Users/montague/raadio/core/manatee.js:203:13)
[ERR]raadiome:     at Object.manatee.manateeCallBackOnMessage (/Users/montague/raadio/core/manatee.js:62:41)
[ERR]raadiome:     at Object.manatee.rebuildData (/Users/montague/raadio/core/manatee.js:107:17)
[ERR]raadiome:     at Socket.<anonymous> (/Users/montague/raadio/core/manatee.js:125:29)
[ERR]raadiome:     at Socket.emit (events.js:107:17)
[ERR]raadiome:     at readableAddChunk (_stream_readable.js:163:16)
[ERR]raadiome:     at Socket.Readable.push (_stream_readable.js:126:10)
[ERR]raadiome:     at TCP.onread (net.js:529:20)
!!!! User raadiome exited with code 1Restarting...

**Comment by Reanmachine** [comment]
Looks like there's a missing null check on this line:

[core/manatee.js:703 @ 34aecbc6120721792829f2806d5acfb938949251](https://github.com/UlysseM/GSBOT/blob/34aecbc6120721792829f2806d5acfb938949251/core/manatee.js#L703)

Should be pretty simple to fix.

**Comment by Tasemu** [comment]
Yup fixed, i would submit a request but tbh im not sure how its done haha

**Comment by UlysseM** [comment]
I'll push a fix tonight.

**Comment by UlysseM** [comment]
Pushing the patch in a moment, sorry for the delay.
