### ISSUE TITLE
plugin config doesn't import properly.

### ISSUE THREAD

**Issue by pironic** [UlysseM/GSBOT#57]
i can't figure out why the callouts plugin doesn't import the config properly. 

2 things i've noticed with the config. It wont' import if the module is the same name as the plugin. It' wont import if the variable is anything other than a string. Callouts plugin utilizes an array in one of the variables. could this be why?

**Comment by UlysseM** [comment]
Could you provide your config?
You should note that it should be a json formatted string, passed through a JSON.parse..
